### ISSUE TITLE
error in open[SOLVED]

### ISSUE THREAD

**Issue by ebad84** [onionj/pybotnet#36]
hey
i'm using this on windows 10, and when i place token and admin id in source and run it, i got this error

```
Traceback (most recent call last):
  File "d:/My-projects/botnet_for_systems_pico_ducky/main.py", line 2, in <module>
    from pybotnet import BotNet, TelegramEngine
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\pybotnet\__init__.py", line 3, in <module>
    from .botnet import BotNet as BotNet
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\pybotnet\botnet.py", line 15, in <module>
    from .context import Context
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\pybotnet\context.py", line 9, in <module>
    class Context:
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\lib\site-packages\pybotnet\context.py", line 37, in Context
    def get_all_global_values(cls) -> dict[Any, Any]:
TypeError: 'type' object is not subscriptable
```
what should i do?

**Comment by ebad84** [comment]
SOLVED!

with python 3.8 i got this error
and there is no problem with python "3.10"

**Comment by onionj** [comment]
Thanks.. I will fix this.
